### ISSUE TITLE
There is a compatibility problem with the web browser plugin

### ISSUE THREAD

**Issue by PPN010** [vrtmrz/ninja-cursor#10]
When you enter the embedded web page provided by the browser plugin and then enter the normal notes, the plugin completely loses its effect and the console displays the following error
👇
caught (in promise) DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is invalid.
    at __moveCursor (plugin:ninja-cursor:100:21)
    at async moveCursor (plugin:ninja-cursor:59:7)

**Comment by vrtmrz** [comment]
Sorry for being late! 
I did not reproduce this but it has probably been fixed at v0.0.13.
Could you please check the behaviour?

**Comment by ConsonanceTrad** [comment]
Yes, the bug disappeared after I updated the plugin, thanks a million,  I'm used to enabling this plugin, and this bug exclusion has greatly improved my experience
