### ISSUE TITLE
Lag in Long Notes

### ISSUE THREAD

**Issue by zcysxy** [vrtmrz/ninja-cursor#4]
Thanks for this plugin!

In short notes, the plugin works fine. However, in longer notes (> 60 lines), the plugin causes some lag in typing, i.e., the letter appears with some delay when typing. The difference can be observed with the plugin turned on and off.

**Comment by vrtmrz** [comment]
Thank you for opening up this issue.
I felt that just like you. And I thought I had solved the problem on version 0.0.4. Have you had a chance to try it? 
Possibly we just missed each other.

**Comment by zcysxy** [comment]
Yes, the current version on my end is 0.0.6. Maybe I'm just being finicky and that's the price for having the cool visual effects 🤣

**Comment by vrtmrz** [comment]
I upgraded Obsidian to v1.0.0, and could reproduce it! 
Fixed at v0.0.7. could you please try this again?

**Comment by zcysxy** [comment]
After some tests, it's much smoother now! Thanks for the fix
