### ISSUE TITLE
Possibilities of modifying the cursor

### ISSUE THREAD

**Issue by ByteMirror** [vrtmrz/ninja-cursor#6]
Hey there, 
first of all, thank you for your amazing work! I really have been looking for something like this for a while and it added a lot of value to Obsidian as a whole for me. 

Now I only have two things missing that I would like to implement in Obsidian and I was wondering if you or maybe someone else knew a way to do this. 

1. Before I had a blue cursor just like on iOS and I would like to get that back. How can I change the cursor color in your Plugin? I tried changing stuff in CSS but it did not work
2. I really want the cursor smooth caret effect that vs code has in Obsidian but I just cant figure out how to do that. 

Do you know a solution to any of these issues I'm having?

Thanks again for your amazing plugin!

**Comment by yarub123** [comment]
Yeah changing the color of the cursor would be wonderful.

**Comment by vrtmrz** [comment]
Sorry for the delay!

To change the cursor colour, we can use the CSS snippet as like below:
```css
* {
    caret-color: red !important;
}
```
(Please change `red` to your favourite colour).

And if you want to overwrite the behaviour too, snippets in  #3 are useful.

**Comment by yarub123** [comment]
@vrtmrz You're good, no rush. Also thank you for that. Caret-color works perfect. 

Quick question, this is not that important just curious:

from snippet 3 The disable movement effect, if I wanted to keep the movement effect, and disable this it doesn't work. 

```
/* Disable movement effect */
.cursorWrapper .x-cursor::after {
    display: none;
}
```

Even if I disable this whole part, it basically removes the whole iA (long blue cursor) from snippet #3 and goes to a default cursor like this. 

Here's the before:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/84487964/219936127-bcc39d31-3462-4ef1-bbe1-f4021d3b32d3.png">

Here's the after (disabling effect above to bring back movement effect):
<img width="237" alt="image" src="https://user-images.githubusercontent.com/84487964/219936153-10cf78d3-f40c-4976-9a4e-02d80bdc30df.png">

Again, not really a big deal. But just wanted to try to keep the iA cursor from #3 ....ANNND keep the movement effect. 

Anyways thank you ♥️

**Comment by vrtmrz** [comment]
@yarub123 
Finally, I understood what is the problem!
I think the following CSS would be nice, could you please try it once?

https://gist.github.com/vrtmrz/c12640a02cdb4102730b9a1938e611a8

**Comment by yarub123** [comment]
@vrtmrz Omg first off sorry I hadn't seen this till now. 

Time fucking flies by SO FAST 😭

Also this CSS made it go from Amazing to FUCKING DELICIOUS. 

It is now PERFECT 👌

Love it man, thank you so very much, appreciate you and your effort. ♥️

**Comment by vrtmrz** [comment]
I am very glad to hear that!

**Comment by yarub123** [comment]
@vrtmrz it's me again, your favorite nightmare 🙃

1. Question on this. When selecting for example 2 lines from the left side only the top line has the cursor blue

2. When selecting the text but from the right side then all the lines are blue. 

I want to get the second option (2.), so that if I select from left side all of them are blue.

Example of (1.) 
<img width="546" alt="image" src="https://github.com/vrtmrz/ninja-cursor/assets/84487964/9ec7f640-53b7-45fe-bb16-588e67fcf2f4">

Example of (2.) this is the one I want but only works when selecting from right side:
<img width="579" alt="image" src="https://github.com/vrtmrz/ninja-cursor/assets/84487964/65f9319d-f56d-45b9-8025-541871809c21">
