### ISSUE TITLE
Ninja Cursor alters mouse clicks in Obsidian ribbon

### ISSUE THREAD

**Issue by trainbuffer** [vrtmrz/ninja-cursor#8]
I use the following CSS to create a drag handlebar in the ribbon:
```
body:not(.is-popout-window) div.side-dock-actions:before {
    content: "\2723";
    font-size: 30px;
    -webkit-app-region: drag;
    text-align: center;
    margin-top:  -9px;
    margin-left: 0px;
}
```
![Screenshot 2023-05-02 071949](https://user-images.githubusercontent.com/3751726/235541614-4d8e1827-b80b-4fc5-b2e1-88d5c18fb988.png)

In a new vault with only Ninja Cursor installed and only the above snippet enabled, dragging/moving the Obsidian window doesn't work. I tried looking for .workspace-ribbon in Ninja Cursor's default CSS and anything to do with the ribbon the main.js, but couldn't find anything. I'm not sure why Ninja Cursor would affect mouse events in the ribbon, but it does. Any advice on a fix or workaround? Thanks! 

Windows 11 Pro 22H2; Obsidian 1.2.6 (installer 1.1.16), Ninja Cursor 0.0.11

**Comment by vrtmrz** [comment]
Thank you for asking me! 
Ninja-cursor is dashing on the invisible layer. I have not been sure why an invisible layer affects window dragging, but thanks to your question, I now understand.

All we need to do is reset this `-webkit-app-region`.

It has been addressed and fixed at v0.0.12. Would you mind if I ask you to try the latest version, please?

**Comment by trainbuffer** [comment]
WOW! That was fast. 

Updated to 0.0.12 and my handlebar window dragging works again! Thank you so much for the fix **and** the fun plugin! 🙏

**Comment by vrtmrz** [comment]
This is your contribution! However, I am really honoured by your grateful words. 
I would like to thank you once again!

**Comment by trainbuffer** [comment]
Just noticed you are based in Osaka. I'm in Kobe. :D ⛩️⚓ Thanks again!
